version: "3"
services:
  jd_scripts1: #默认
    image: zhaozhanzhan/jd_scripts
    # 配置服务器资源约束。此例子中服务被限制为使用内存不超过200M以及cpu不超过 0.2（单核的20%）
    # 经过实际测试，建议不低于200M
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.2'
    #       memory: 200M
    restart: always
    container_name: jd_scripts1
    tty: true
    volumes:
      - ./logs1:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
      # 互助助码等参数可自行增加，如下。
      # 京东种豆得豆
      # - PLANT_BEAN_SHARECODES=
      
  jd_scripts2: #默认
    image: zhaozhanzhan/jd_scripts
    restart: always
    container_name: jd_scripts2
    tty: true
    volumes:
      - ./logs2:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
  jd_scripts4: #自定义追加默认之后
    image: zhaozhanzhan/jd_scripts
    restart: always
    container_name: jd_scripts4
    tty: true
    volumes:
      - ./logs4:/scripts/logs
      - ./my_crontab_list4.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
      - CUSTOM_LIST_FILE=my_crontab_list.sh
  jd_scripts5: #自定义覆盖默认
    image: zhaozhanzhan/jd_scripts
    restart: always
    container_name: jd_scripts5
    tty: true
    volumes:
      - ./logs5:/scripts/logs
      - ./my_crontab_list5.sh:/scripts/docker/my_crontab_list.sh
    environment:
      - JD_COOKIE=pt_key=AAJfjaNrADAS8ygfgIsOxxxxxxxKpfDaZ2pSBOYTxtPqLK8U1Q;pt_pin=lxxxxxx5;
      - TG_BOT_TOKEN=130xxxx280:AAExxxxxxWP10zNf91WQ
      - TG_USER_ID=12xxxx206
      - CUSTOM_LIST_FILE=my_crontab_list.sh
      - CUSTOM_LIST_MERGE_TYPE=overwrite
