on:
  push:
    branches:
      -master
  schedule:
    - cron: 0 4/12 * * *   # 每隔12小时
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }} # 令牌
          upstream_repository: JDHelloWorld/jd_scripts. # 上游仓库
          target_repository: SkyJohn233/jd_scripts # 你要推送的仓库
          upstream_branch: main # 默认是拉取上游仓库的master分支
          target_branch: main # 默认推送到你的仓库master分支
          force: true # 是否强制推送
          tags: true # 确定是否使用-tags
